AWSTemplateFormatVersion: "2010-09-09"

Description: HW3 CloudFormation Stack

Resources:
  B1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bk00119-photos-b1-stack
      WebsiteConfiguration:
        IndexDocument: index.html

  B1Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref B1
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: arn:aws:s3:::bk00119-photos-b1-stack/*

  B2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bk00119-photos-b2-stack

  B2Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref B2
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAPIGatewayPutObject
            Effect: Allow
            Principal:
              AWS: !GetAtt ApiGatewayRole.Arn
            Action: s3:PutObject
            Resource: arn:aws:s3:::bk00119-photos-b2-stack/*
          - Sid: AllowPublicReadObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: arn:aws:s3:::bk00119-photos-b2-stack/*

  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: photos-api-gateway-stack-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  LambdaIndexRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: index-photos-stack-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRekognitionReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaSearchRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: search-photos-stack-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonLexRunBotsOnly
        - arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LF1:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: index-photos-stack
      Runtime: python3.14
      Handler: index_photos_lambda.lambda_handler
      Role: !GetAtt LambdaIndexRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "LF1"}
      Timeout: 20

  LF2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: search-photos-stack
      Runtime: python3.14
      Handler: search_photos_lambda.lambda_handler
      Role: !GetAtt LambdaSearchRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "LF2"}
      Timeout: 20

  API:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: photo-search-api-stack

  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref API
      StageName: dev
    DependsOn: API

Outputs:
  FrontendURL:
    Value: !GetAtt B1.WebsiteURL
